"""empty message

Revision ID: 61c175944656
Revises: ac8884aaa9e2
Create Date: 2022-09-10 19:29:47.595973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c175944656'
down_revision = 'ac8884aaa9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('hugo_col', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'hugo_col')
    # ### end Alembic commands ###
